name: payflow
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_card: ^2.0.0
  camera: ^0.9.4+3
  cupertino_icons: ^1.0.2
  firebase_core: ^1.8.0
  flutter:
    sdk: flutter
  flutter_masked_text2: ^0.9.1
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  google_ml_kit: ^0.7.2
  google_sign_in: ^5.2.0
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
